[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
# [[plugins]]
# repo = 'andviro/flake8-vim'
# on_ft = ['python']
# [[plugins]]
# repo = 'tell-k/vim-autopep8'
# on_ft = ['python']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft=['dart']
[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft=['dart']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
